# Generated by Django 5.2.8 on 2025-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
            ],
        ),
    ]
